Add SBOM protos
grafeas/grafeas pull request #501
Opened 2021-08-11 14:50 UTC by alowayed

Closes #500

2021-08-11 23:44 UTC, aysylu requested changes
Could you please move these for now to v1beta1, so we can iterate with Kate Stewart and the community on the nuances of the representation? Once it's settled, we can copy these into v1.

2021-08-11 23:44 UTC, aysylu commented on proto/v1/sbom.proto
> +  // This field provides a place for the SPDX file creator to record any
could you please add a TODO to create a License proto that'd encapsulate this and be used everywhere?

2021-08-11 23:44 UTC, aysylu commented on proto/v1/sbom.proto
> +message RelationshipNote {}
this is something we postponed the discussion on for the best way to represent, let's remove this for now and re-open the conversation internally? ditto for RelationshipOccurrence

2021-08-12 16:46 UTC, aysylu approved these changes

2021-08-12 18:05 UTC, wkozlik approved these changes

2021-08-12 18:06 UTC, merged